Make iterate() lazily evaluated on wasm
tursodatabase/limbo pull request #527
Opened 2024-12-20 20:23 UTC by diegoreis42

#514 

Introduces a new feature for lazy evaluation in the `Statement.raw().iterate()` method and includes related changes in both the test and implementation files. The most important changes include adding a test case for lazy evaluation, creating a `RowIterator` struct, and modifying the `iterate` method to use this new struct.

Everything seems to works fine, but suggestions on code improvement and test use cases are welcoming.

2024-12-21 06:48 UTC, penberg commented
@diegoreis42 Looks great! I am guessing some auto-formatted turned the diff on the test file into something that's pretty unreadable. Can you please change back to 4 space indent to make that change readable?

2024-12-21 09:46 UTC, Lemon-Peppermint commented
@diegoreis42 FYI, `js_sys::Array` implements `FromIterator`, you could move your `RowIterator.next()` method to an implementation of `Iterator` then use that to construct your `Array` instead of going through an intermediate `Object`.

2024-12-21 14:24 UTC, diegoreis42 commented
> @diegoreis42 Looks great! I am guessing some auto-formatted turned the diff on the test file into something that's pretty unreadable. Can you please change back to 4 space indent to make that change readable?

Yeah sure, sorry about that.

2024-12-21 22:39 UTC, diegoreis42 commented
Hey, I thought that the CI test suit would run wasm tests but it seems it doesn't. Some changes are needed to conform with previous tests, I'm working on this.

In order to test if the rows are lazily loaded, I wrote a SQL trigger, but it has not been implemented yet by Limbo, so it throws a error.  Any inputs in how test if the rows are lazily loaded?

Btw, perhaps it would be nice to include wasm testing on CI, I can try do this in another PR.

2024-12-26 17:15 UTC, diegoreis42 commented
@penberg in the iterator, when a row is busy it returns undefined, it's fine or other behavior is required?

2024-12-26 18:15 UTC, pereman2 requested changes
Can you rebase, it will be unreviewable if I cannot find the changes.

2024-12-26 18:41 UTC, diegoreis42 commented
> Can you rebase, it will be unreviewable if I cannot find the changes.

Done.

2025-01-05 18:23 UTC, merged