Stub clock
tursodatabase/limbo pull request #586
Opened 2024-12-31 14:55 UTC by PlasmaIntec

Makes clock deterministic for test scenarios.

https://github.com/tursodatabase/limbo/issues/439

2024-12-31 15:29 UTC, pereman2 requested changes
I think we would prefer to have clock inside the IO layer. Because this is also a problem that we have in simulator, and the simulator basically implements the IO differently.

2024-12-31 20:30 UTC, PlasmaIntec commented
Can you explain more how this is a problem in simulator? I don't see any usages of the `get_current_time` fn implemented for the `IO` trait [[code](https://github.com/search?q=repo%3Atursodatabase/limbo%20get_current_time&type=code)].

2025-01-04 08:22 UTC, penberg commented
Hey @PlasmaIntec, what @pereman2 is saying is that we should fix `get_current_time()` in the `IO` trait instead of introducing a separate clock. The purpose of IO is to abstract all non-deterministic behavior in one place for simpler simulation.

2025-02-04 00:12 UTC, penberg commented
This pull request has been marked as stale due to inactivity. It will be closed in 7 days if no further activity occurs.

2025-02-12 00:12 UTC, penberg commented
This pull request has been closed due to inactivity. Please feel free to reopen it if you have further updates.

2025-02-12 00:12 UTC, closed without merging